### ISSUE TITLE
Feature request: Toggle command for enabling/disabling inline completions

### ISSUE THREAD

**Issue by machado-t** [taichimaeda/markpilot#1]
While I appreciate the current options to explicitly enable and disable completions, having a single command to toggle the feature on or off would be incredibly useful, particularly when mapping this function to a ribbon button or a keyboard shortcut.
Thanks

**Comment by taichimaeda** [comment]
Thanks for raising this.

I've just added commands to toggle completions, chat view and cache (not just enable/disable), as well a ribbon action item to toggle completions in PR #3 - I'll merge this when I'm done with some refactoring.
